import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  AnalysisResult,
  Scenario,
  EnhancedFix,
  FixSuggestions,
  FlowType,
  Transcript,
} from '@/types';
import { AggregatedScenario } from './aggregateScenarios';

interface ExportData {
  flowType: FlowType;
  transcripts: Transcript[];
  results?: AnalysisResult | null;
  fixes?: FixSuggestions | null;
  scenarioResults?: { scenarios: Scenario[] } | null;
  enhancedFixes?: { fixes: EnhancedFix[] } | null;
  aggregatedScenarios?: AggregatedScenario[];
  analysisDate?: string;
  referenceScript?: string;
}

// ============= CSV/EXCEL EXPORT =============

export function generateComprehensiveExcel(data: ExportData): void {
  const workbook = XLSX.utils.book_new();
  const timestamp = new Date().toISOString().split('T')[0];

  // Sheet 1: Executive Summary
  const summarySheet = generateExecutiveSummary(data);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Executive Summary');

  // Sheet 2: Call-Level Summary
  const callSummarySheet = generateCallSummary(data);
  XLSX.utils.book_append_sheet(workbook, callSummarySheet, 'Call Summary');

  // Sheet 3: Detailed Issues/Scenarios
  if (data.flowType === 'open-ended' && data.scenarioResults) {
    const detailsSheet = generateScenarioDetails(data.scenarioResults.scenarios);
    XLSX.utils.book_append_sheet(workbook, detailsSheet, 'Detailed Scenarios');
  } else if (data.flowType === 'objective' && data.results) {
    const detailsSheet = generateIssueDetails(data.results);
    XLSX.utils.book_append_sheet(workbook, detailsSheet, 'Detailed Issues');
  }

  // Sheet 4: Aggregated Patterns
  if (data.aggregatedScenarios && data.aggregatedScenarios.length > 0) {
    const patternsSheet = generateAggregatedPatterns(data.aggregatedScenarios);
    XLSX.utils.book_append_sheet(workbook, patternsSheet, 'Aggregated Patterns');
  }

  // Sheet 5: Fix Recommendations
  if (data.enhancedFixes && data.enhancedFixes.fixes.length > 0) {
    const fixesSheet = generateFixRecommendations(data.enhancedFixes.fixes);
    XLSX.utils.book_append_sheet(workbook, fixesSheet, 'Fix Recommendations');
  } else if (data.fixes && (data.fixes.scriptFixes.length > 0 || data.fixes.generalFixes.length > 0)) {
    const fixesSheet = generateObjectiveFixRecommendations(data.fixes);
    XLSX.utils.book_append_sheet(workbook, fixesSheet, 'Fix Recommendations');
  }

  // Sheet 6: Metrics Dashboard
  const metricsSheet = generateMetricsDashboard(data);
  XLSX.utils.book_append_sheet(workbook, metricsSheet, 'Metrics');

  // Download the file
  XLSX.writeFile(workbook, `AI_Agent_Analysis_Report_${timestamp}.xlsx`);
}

function generateExecutiveSummary(data: ExportData): XLSX.WorkSheet {
  const totalCalls = data.transcripts.length;
  const analysisDate = data.analysisDate || new Date().toLocaleString();

  let totalIssues = 0;
  let callsWithIssues = 0;
  let avgSeverity = 'N/A';

  if (data.flowType === 'open-ended' && data.scenarioResults) {
    totalIssues = data.scenarioResults.scenarios.length;
    const callsWithScenariosSet = new Set(data.scenarioResults.scenarios.map(s => s.callId));
    callsWithIssues = callsWithScenariosSet.size;
  } else if (data.flowType === 'objective' && data.results) {
    totalIssues = data.results.issues.length;
    callsWithIssues = data.results.callsWithIssues;
  }

  const healthScore = totalCalls > 0 ? Math.round(((totalCalls - callsWithIssues) / totalCalls) * 100) : 0;

  const summaryData = [
    ['AI Agent Control Center - Analysis Report'],
    [''],
    ['Metric', 'Value'],
    ['Analysis Date', analysisDate],
    ['Flow Type', data.flowType === 'open-ended' ? 'Open-Ended Analysis' : 'Objective Checks'],
    ['Total Calls Analyzed', totalCalls],
    ['Calls with Issues', callsWithIssues],
    ['Total Issues/Scenarios Found', totalIssues],
    ['Clean Calls', totalCalls - callsWithIssues],
    ['Overall Health Score', `${healthScore}%`],
    [''],
    ['Report Generated By', 'AI Agent Control Center'],
    ['Export Date', new Date().toLocaleString()],
  ];

  return XLSX.utils.aoa_to_sheet(summaryData);
}

function generateCallSummary(data: ExportData): XLSX.WorkSheet {
  const headers = ['Call ID', 'Total Issues/Scenarios', 'Highest Severity', 'Status', 'Issue Types'];

  const rows = data.transcripts.map(transcript => {
    let issueCount = 0;
    let highestSeverity = 'Clean';
    let issueTypes: string[] = [];

    if (data.flowType === 'open-ended' && data.scenarioResults) {
      const callScenarios = data.scenarioResults.scenarios.filter(s => s.callId === transcript.id);
      issueCount = callScenarios.length;

      if (callScenarios.length > 0) {
        const severities = callScenarios.map(s => s.severity);
        if (severities.includes('critical')) highestSeverity = 'Critical';
        else if (severities.includes('high')) highestSeverity = 'High';
        else if (severities.includes('medium')) highestSeverity = 'Medium';
        else highestSeverity = 'Low';

        issueTypes = [...new Set(callScenarios.map(s => s.title))];
      }
    } else if (data.flowType === 'objective' && data.results) {
      const callIssues = data.results.issues.filter(i => i.callId === transcript.id);
      issueCount = callIssues.length;

      if (callIssues.length > 0) {
        const severities = callIssues.map(i => i.severity);
        if (severities.includes('critical')) highestSeverity = 'Critical';
        else if (severities.includes('high')) highestSeverity = 'High';
        else if (severities.includes('medium')) highestSeverity = 'Medium';
        else highestSeverity = 'Low';

        issueTypes = [...new Set(callIssues.map(i => i.type))];
      }
    }

    const status = issueCount === 0 ? '✓ Pass' : highestSeverity === 'Critical' || highestSeverity === 'High' ? '⚠ Needs Review' : '⚡ Minor Issues';

    return [
      transcript.id,
      issueCount,
      highestSeverity,
      status,
      issueTypes.join('; ')
    ];
  });

  return XLSX.utils.aoa_to_sheet([headers, ...rows]);
}

function generateScenarioDetails(scenarios: Scenario[]): XLSX.WorkSheet {
  const headers = [
    'Call ID',
    'Title',
    'Audit Dimension',
    'Root Cause Type',
    'Context',
    'What Happened',
    'Impact',
    'Suggested Action',
    'Severity',
    'Confidence (%)',
    'Line Numbers',
  ];

  const rows = scenarios.map(scenario => [
    scenario.callId,
    scenario.title,
    scenario.dimension || 'N/A',
    scenario.rootCauseType || 'N/A',
    scenario.context,
    scenario.whatHappened,
    scenario.impact,
    'Review and implement recommended fixes', // Generic suggested action
    scenario.severity,
    scenario.confidence,
    scenario.lineNumbers.join('; '),
  ]);

  return XLSX.utils.aoa_to_sheet([headers, ...rows]);
}

function generateIssueDetails(results: AnalysisResult): XLSX.WorkSheet {
  const headers = [
    'Call ID',
    'Issue Type',
    'Severity',
    'Confidence (%)',
    'Evidence',
    'Explanation',
    'Suggested Fix',
    'Root Cause Type',
    'Line Numbers',
  ];

  const rows = results.issues.map(issue => [
    issue.callId,
    issue.type,
    issue.severity,
    Math.round(issue.confidence * 100),
    issue.evidenceSnippet,
    issue.explanation,
    issue.suggestedFix || 'See fix recommendations',
    issue.rootCauseType || 'N/A',
    issue.lineNumbers.join('; '),
  ]);

  return XLSX.utils.aoa_to_sheet([headers, ...rows]);
}

function generateAggregatedPatterns(aggregated: AggregatedScenario[]): XLSX.WorkSheet {
  const headers = [
    'Pattern Title',
    'Audit Dimension',
    'Root Cause Type',
    'Pattern Description',
    'Severity',
    'Avg Confidence (%)',
    'Total Occurrences',
    'Unique Calls Affected',
    'Affected Call IDs',
  ];

  const rows = aggregated.map(agg => [
    agg.title,
    agg.dimension,
    agg.rootCauseType || 'N/A',
    agg.pattern,
    agg.severity,
    agg.avgConfidence.toFixed(1),
    agg.occurrences,
    agg.uniqueCalls,
    agg.affectedCallIds.join('; '),
  ]);

  return XLSX.utils.aoa_to_sheet([headers, ...rows]);
}

function generateFixRecommendations(fixes: EnhancedFix[]): XLSX.WorkSheet {
  const headers = [
    'Priority',
    'Fix Title',
    'Fix Type',
    'Root Cause Category',
    'Root Cause Explanation',
    'Suggested Solution',
    'Where to Implement',
    'What to Implement',
    'Concrete Example',
    'Success Criteria',
    'How to Test',
  ];

  const rows = fixes.map((fix, index) => {
    const priority = index < 3 ? 'P0 - Critical' : index < 6 ? 'P1 - High' : 'P2 - Medium';

    return [
      priority,
      fix.title,
      fix.fixType,
      fix.rootCauseType,
      fix.rootCause,
      fix.suggestedSolution,
      fix.whereToImplement,
      fix.whatToImplement,
      typeof fix.concreteExample === 'string' ? fix.concreteExample : JSON.stringify(fix.concreteExample),
      fix.successCriteria,
      fix.howToTest,
    ];
  });

  return XLSX.utils.aoa_to_sheet([headers, ...rows]);
}

function generateObjectiveFixRecommendations(fixes: FixSuggestions): XLSX.WorkSheet {
  const headers = [
    'Category',
    'Issue Type',
    'Problem',
    'Suggestion',
    'Placement Hint',
    'Example Response',
    'Root Cause Type',
  ];

  const scriptRows = fixes.scriptFixes.map(fix => [
    'Script Fix',
    fix.issueType,
    fix.problem,
    fix.suggestion,
    fix.placementHint,
    fix.exampleResponse,
    fix.rootCauseType || 'N/A',
  ]);

  const generalRows = fixes.generalFixes.map(fix => [
    'General Fix',
    fix.issueType,
    fix.problem,
    fix.suggestion,
    fix.placementHint,
    fix.exampleResponse,
    fix.rootCauseType || 'N/A',
  ]);

  return XLSX.utils.aoa_to_sheet([headers, ...scriptRows, ...generalRows]);
}

function generateMetricsDashboard(data: ExportData): XLSX.WorkSheet {
  const metricsData: any[][] = [['Metric', 'Count', 'Percentage']];

  if (data.flowType === 'open-ended' && data.scenarioResults) {
    const scenarios = data.scenarioResults.scenarios;
    const total = scenarios.length;

    // By Severity
    metricsData.push(['=== By Severity ===', '', '']);
    const bySeverity = scenarios.reduce((acc, s) => {
      acc[s.severity] = (acc[s.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    Object.entries(bySeverity).forEach(([severity, count]) => {
      metricsData.push([severity, count, `${((count / total) * 100).toFixed(1)}%`]);
    });

    // By RCA Type
    metricsData.push(['', '', '']);
    metricsData.push(['=== By Root Cause ===', '', '']);
    const byRCA = scenarios.reduce((acc, s) => {
      const rca = s.rootCauseType || 'Unknown';
      acc[rca] = (acc[rca] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    Object.entries(byRCA).forEach(([rca, count]) => {
      metricsData.push([rca, count, `${((count / total) * 100).toFixed(1)}%`]);
    });

    // By Dimension
    metricsData.push(['', '', '']);
    metricsData.push(['=== By Audit Dimension ===', '', '']);
    const byDimension = scenarios.reduce((acc, s) => {
      const dim = s.dimension || 'Unknown';
      acc[dim] = (acc[dim] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    Object.entries(byDimension).forEach(([dim, count]) => {
      metricsData.push([dim, count, `${((count / total) * 100).toFixed(1)}%`]);
    });
  } else if (data.flowType === 'objective' && data.results) {
    const issues = data.results.issues;
    const total = issues.length;

    // By Severity
    metricsData.push(['=== By Severity ===', '', '']);
    Object.entries(data.results.severityDistribution).forEach(([severity, count]) => {
      metricsData.push([severity, count, `${((count / total) * 100).toFixed(1)}%`]);
    });

    // By Type
    metricsData.push(['', '', '']);
    metricsData.push(['=== By Issue Type ===', '', '']);
    Object.entries(data.results.issuesByType).forEach(([type, count]) => {
      metricsData.push([type, count, `${((count / total) * 100).toFixed(1)}%`]);
    });
  }

  return XLSX.utils.aoa_to_sheet(metricsData);
}

// ============= PDF EXPORT =============

export function generateComprehensivePDF(data: ExportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPos = 20;

  // Cover Page
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Agent Control Center', pageWidth / 2, yPos, { align: 'center' });

  yPos += 10;
  doc.setFontSize(18);
  doc.text('Analysis Report', pageWidth / 2, yPos, { align: 'center' });

  yPos += 20;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  const totalCalls = data.transcripts.length;
  let totalIssues = 0;
  let callsWithIssues = 0;

  if (data.flowType === 'open-ended' && data.scenarioResults) {
    totalIssues = data.scenarioResults.scenarios.length;
    callsWithIssues = new Set(data.scenarioResults.scenarios.map(s => s.callId)).size;
  } else if (data.flowType === 'objective' && data.results) {
    totalIssues = data.results.issues.length;
    callsWithIssues = data.results.callsWithIssues;
  }

  const healthScore = totalCalls > 0 ? Math.round(((totalCalls - callsWithIssues) / totalCalls) * 100) : 0;

  // Executive Summary
  doc.setFillColor(240, 240, 250);
  doc.rect(20, yPos, pageWidth - 40, 60, 'F');

  yPos += 10;
  doc.setFontSize(10);
  doc.text(`Analysis Date: ${data.analysisDate || new Date().toLocaleString()}`, 25, yPos);
  yPos += 8;
  doc.text(`Flow Type: ${data.flowType === 'open-ended' ? 'Open-Ended Analysis' : 'Objective Checks'}`, 25, yPos);
  yPos += 8;
  doc.text(`Total Calls Analyzed: ${totalCalls}`, 25, yPos);
  yPos += 8;
  doc.text(`Calls with Issues: ${callsWithIssues}`, 25, yPos);
  yPos += 8;
  doc.text(`Total Issues/Scenarios: ${totalIssues}`, 25, yPos);
  yPos += 8;
  doc.setFont('helvetica', 'bold');
  doc.text(`Overall Health Score: ${healthScore}%`, 25, yPos);
  doc.setFont('helvetica', 'normal');

  // Add charts/visualizations
  doc.addPage();
  yPos = 20;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Overview', 20, yPos);
  yPos += 15;

  // Add tables for detailed data
  if (data.flowType === 'open-ended' && data.scenarioResults) {
    addScenariosToPDF(doc, data.scenarioResults.scenarios);
  } else if (data.flowType === 'objective' && data.results) {
    addIssuesToPDF(doc, data.results);
  }

  // Add fix recommendations
  if (data.enhancedFixes && data.enhancedFixes.fixes.length > 0) {
    doc.addPage();
    addFixesToPDF(doc, data.enhancedFixes.fixes);
  }

  // Save PDF
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`AI_Agent_Analysis_Report_${timestamp}.pdf`);
}

function addScenariosToPDF(doc: jsPDF, scenarios: Scenario[]): void {
  const tableData = scenarios.slice(0, 20).map(s => [
    s.callId,
    s.title.substring(0, 30),
    s.severity,
    s.rootCauseType || 'N/A',
    `${s.confidence}%`,
  ]);

  autoTable(doc, {
    head: [['Call ID', 'Title', 'Severity', 'RCA Type', 'Confidence']],
    body: tableData,
    startY: 40,
    theme: 'grid',
    headStyles: { fillColor: [66, 139, 202] },
    styles: { fontSize: 8 },
  });

  // Add summary text
  const finalY = (doc as any).lastAutoTable.finalY || 40;
  doc.setFontSize(10);
  doc.text(`Showing top 20 of ${scenarios.length} scenarios`, 20, finalY + 10);
}

function addIssuesToPDF(doc: jsPDF, results: AnalysisResult): void {
  const tableData = results.issues.slice(0, 20).map(issue => [
    issue.callId,
    issue.type,
    issue.severity,
    `${Math.round(issue.confidence * 100)}%`,
    issue.explanation.substring(0, 50) + '...',
  ]);

  autoTable(doc, {
    head: [['Call ID', 'Type', 'Severity', 'Confidence', 'Explanation']],
    body: tableData,
    startY: 40,
    theme: 'grid',
    headStyles: { fillColor: [66, 139, 202] },
    styles: { fontSize: 8 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 40;
  doc.setFontSize(10);
  doc.text(`Showing top 20 of ${results.issues.length} issues`, 20, finalY + 10);
}

function addFixesToPDF(doc: jsPDF, fixes: EnhancedFix[]): void {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Fix Recommendations', 20, 20);

  const tableData = fixes.slice(0, 15).map((fix, idx) => {
    const priority = idx < 3 ? 'P0' : idx < 6 ? 'P1' : 'P2';
    return [
      priority,
      fix.title.substring(0, 40),
      fix.fixType,
      fix.rootCauseType,
    ];
  });

  autoTable(doc, {
    head: [['Priority', 'Fix Title', 'Type', 'RCA Category']],
    body: tableData,
    startY: 30,
    theme: 'grid',
    headStyles: { fillColor: [40, 167, 69] },
    styles: { fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 30;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Showing top 15 of ${fixes.length} recommendations`, 20, finalY + 10);
}
